### ISSUE TITLE
acces the http requests

### ISSUE THREAD

**Issue by ghost** [lifeemotions/websocketproxy#5]
Is there a way to access the http requests?

**Comment by TiagoOliveiraMarques** [comment]
The proxy works on top of TCP (except during the initial connection, when we want to check if the client wants to connect to the HTTP server or the websocket server).

You could access the TCP streams, but I don't see the point in this.

The upstream server framework you are using (asp.net, nancy,...) should have means to access the http request data.

**Comment by ghost** [comment]
I see, thanks for the reply.
